Bu analiz,
1977'den bugune kadar USA'de islenen cinayetlerin;
sanigin, kurbanin irkina ve sanigin olum cezasi alip almamasina gore Odds Orani ile degerlendirilmesini kapsar.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
#https://deathpenaltyinfo.org/policy-issues/race
df1=pd.read_csv('data1.csv', encoding='utf-8', sep=';')

In [3]:
df1.head()

Race of Victims (Multiple races including white)     State   Race  \
0                                            White      Utah  White   
1                                            White   Florida  White   
2                                            White    Nevada  White   
3                                            White   Indiana  White   
4                                            White  Virginia  White   

  Execution Volunteer        Foreign National   Region   Sex    Table Name  
0           Volunteer  Not a Foreign National     West  Male  ExecutionsPS  
1     Not a Volunteer  Not a Foreign National    South  Male  ExecutionsPS  
2           Volunteer  Not a Foreign National     West  Male  ExecutionsPS  
3           Volunteer  Not a Foreign National  Midwest  Male  ExecutionsPS  
4           Volunteer  Not a Foreign National    South  Male  ExecutionsPS

Sadece sanigin ve kurbanin irkinin siyah ve beyaz olmasi ve sanigin olum cezasi alip almayacagi ile ilgilendigimizden diger sutunlari dikkate almayacagiz. 

In [4]:
k=df1.loc[df1['Race of Victims (Multiple races including white)'].isin(['Black', 'White']) & 
       df1['Race'].isin(['Black', 'White'])]

In [5]:
df=pd.crosstab([k['Race of Victims (Multiple races including white)'],k['Race'],k['Execution Volunteer']], k['Table Name'])

In [6]:
df

Table Name                                                                  ExecutionsPS
Race of Victims (Multiple races including white) Race  Execution Volunteer              
Black                                            Black Not a Volunteer               174
                                                       Volunteer                       2
                                                 White Not a Volunteer                18
                                                       Volunteer                       3
White                                            Black Not a Volunteer               289
                                                       Volunteer                       5
                                                 White Not a Volunteer               659
                                                       Volunteer                     116

In [7]:
df=df.reset_index()

In [8]:
df

Table Name Race of Victims (Multiple races including white)   Race  \
0                                                     Black  Black   
1                                                     Black  Black   
2                                                     Black  White   
3                                                     Black  White   
4                                                     White  Black   
5                                                     White  Black   
6                                                     White  White   
7                                                     White  White   

Table Name Execution Volunteer  ExecutionsPS  
0              Not a Volunteer           174  
1                    Volunteer             2  
2              Not a Volunteer            18  
3                    Volunteer             3  
4              Not a Volunteer           289  
5                    Volunteer             5  
6              Not a Volunteer           659  
7                    Volunteer           116

In [9]:
table1=pd.crosstab(df["Race"],df["Race of Victims (Multiple races including white)"], values=df.ExecutionsPS, aggfunc='sum')

In [10]:
table2=pd.crosstab(df["Race"],df["Execution Volunteer"], values=df.ExecutionsPS, aggfunc='sum')

In [11]:
table3=pd.crosstab(df["Race of Victims (Multiple races including white)"],df["Execution Volunteer"], values=df.ExecutionsPS, aggfunc='sum')

In [12]:
table1=table1.to_numpy();
table2=table2.to_numpy();
table3=table3.to_numpy();

In [13]:
print(table1)

[[176 294]
 [ 21 775]]


In [14]:
oddsratio, pvalue = stats.fisher_exact(table1)
print("OddsR: ", oddsratio, "p-Value:", pvalue)

OddsR:  22.0926465824425 p-Value: 3.1069186869995866e-62


In [15]:
print('Sanigin irki biliniyorken kurbanin irkinin beyaz olmasi olasiligi siyah olmasi olasiliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin irki biliniyorken kurbanin irkinin beyaz olmasi olasiligi siyah olmasi olasiliginin 22.09 katidir.


In [16]:
print(table2)

[[463   7]
 [677 119]]


In [17]:
oddsratio, pvalue = stats.fisher_exact(table2)
print("OddsR: ", oddsratio, "p-Value:", pvalue)

OddsR:  11.62629246676514 p-Value: 6.250720998771805e-18


In [18]:
print('Sanigin olum cezasi karari bilindiginde beyaz irkli saniklarin orani siyah irkli saniklarin oraninin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi karari bilindiginde beyaz irkli saniklarin orani siyah irkli saniklarin oraninin 11.63 katidir.


In [19]:
print(table3)

[[192   5]
 [948 121]]


In [20]:
oddsratio, pvalue = stats.fisher_exact(table3)
print("OddsR: ", oddsratio, "p-Value:", pvalue)

OddsR:  4.9012658227848105 p-Value: 2.705871430488996e-05


In [21]:
print('Sanigin olum cezasi karari bilindiginde kurbanin beyaz olma olasiligi siyah olmasi olasiliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi karari bilindiginde kurbanin beyaz olma olasiligi siyah olmasi olasiliginin 4.9 katidir.


# Sanigin Irki Sabit Tutuldugunda

In [22]:
sanik_beyaz_ise=df.loc[df["Race"]=='White'];
table4=pd.crosstab(sanik_beyaz_ise["Race of Victims (Multiple races including white)"],sanik_beyaz_ise["Execution Volunteer"], values=sanik_beyaz_ise.ExecutionsPS, aggfunc='sum');
table4=table4.to_numpy();
table4=table4+1;
oddsratio, pvalue = stats.fisher_exact(table4)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  0.8420454545454545 p-Value: 0.7666522940569249


In [23]:
table4

array([[ 19,   4],
       [660, 117]], dtype=int64)

In [24]:
print('Sanigin olum cezasi karari bilindiginde kurbanin beyaz olma olasiligi siyah olmasi olasiliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi karari bilindiginde kurbanin beyaz olma olasiligi siyah olmasi olasiliginin 0.84 katidir.


In [25]:
sanik_siyah_ise=df.loc[df["Race"]=='Black'];
table5=pd.crosstab(sanik_siyah_ise["Race of Victims (Multiple races including white)"],sanik_siyah_ise["Execution Volunteer"], values=sanik_siyah_ise.ExecutionsPS, aggfunc='sum');
table5=table5.to_numpy();
oddsratio, pvalue = stats.fisher_exact(table5)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  1.505190311418685 p-Value: 1.0


In [26]:
print('Sanigin olum cezasi karari bilindiginde kurbanin siyah olma olasiligi beyaz olmasi olasiliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi karari bilindiginde kurbanin siyah olma olasiligi beyaz olmasi olasiliginin 1.51 katidir.


# Kurbanin Irki Sabit Tutuldugunda

In [27]:
kurban_beyaz_ise=df.loc[df["Race of Victims (Multiple races including white)"]=='White']
table6=pd.crosstab(df["Race"],df["Execution Volunteer"], values=df.ExecutionsPS, aggfunc='sum');
table6=table6.to_numpy();
oddsratio, pvalue = stats.fisher_exact(table6)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  11.62629246676514 p-Value: 6.250720998771805e-18


In [28]:
table6

array([[463,   7],
       [677, 119]], dtype=int64)

In [29]:
print('Kurbanin beyaz oldugu ve sanigin olum cezasi karari bilindiginde sanigin beyaz olmasi siyah olma olasikliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Kurbanin beyaz oldugu ve sanigin olum cezasi karari bilindiginde sanigin beyaz olmasi siyah olma olasikliginin 11.63 katidir.


In [30]:
kurban_siyah_ise=df.loc[df["Race of Victims (Multiple races including white)"]=='Black']
table7=pd.crosstab(kurban_siyah_ise["Race"],kurban_siyah_ise["Execution Volunteer"], values=kurban_siyah_ise.ExecutionsPS, aggfunc='sum');
table7=table7.to_numpy();
oddsratio, pvalue = stats.fisher_exact(table7)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  14.5 p-Value: 0.009175455013714083


In [31]:
table7

array([[174,   2],
       [ 18,   3]], dtype=int64)

In [32]:
print('Kurbanin siyah oldugu ve sanigin olum cezasi karari bilindiginde sanigin beyaz olmasi siyah olma olasikliginin ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Kurbanin siyah oldugu ve sanigin olum cezasi karari bilindiginde sanigin beyaz olmasi siyah olma olasikliginin 14.5 katidir.


# Olum Cezasi Sabit Tutuldugunda

In [33]:
olum_cezasi_aldi_ise=df.loc[df["Execution Volunteer"]=='Volunteer']
table8=pd.crosstab(olum_cezasi_aldi_ise["Race"],olum_cezasi_aldi_ise["Race of Victims (Multiple races including white)"], values=olum_cezasi_aldi_ise.ExecutionsPS, aggfunc='sum');
table8=table8.to_numpy();
table8=table8+0.5;
oddsratio, pvalue = stats.fisher_exact(table8)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  15.466666666666667 p-Value: 0.0245682372212405


In [34]:
table8

array([[  2.5,   5.5],
       [  3.5, 116.5]])

In [35]:
print('Sanigin olum cezasi aldigi ve irkinin beyaz oldugu biliniyorken kurbanin beyaz olma olasiligi  ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi aldigi ve irkinin beyaz oldugu biliniyorken kurbanin beyaz olma olasiligi  15.47 katidir.


In [36]:
olum_cezasi_almadi_ise=df.loc[df["Execution Volunteer"]=='Not a Volunteer']
table9=pd.crosstab(olum_cezasi_almadi_ise["Race"],olum_cezasi_almadi_ise["Race of Victims (Multiple races including white)"], values=olum_cezasi_almadi_ise.ExecutionsPS, aggfunc='sum');
table9=table9.to_numpy();
oddsratio, pvalue = stats.fisher_exact(table9)
print("OddsR: ", oddsratio, "p-Value:", pvalue);

OddsR:  22.042675893886965 p-Value: 6.228333370385627e-57


In [37]:
table9

array([[174, 289],
       [ 18, 659]], dtype=int64)

In [38]:
print('Sanigin olum cezasi aldigi ve irkinin beyaz oldugu biliniyorken kurbanin siyah olma olasiligi  ' 
      + str(oddsratio.round(2))+ 
      ' katidir.')

Sanigin olum cezasi aldigi ve irkinin beyaz oldugu biliniyorken kurbanin siyah olma olasiligi  22.04 katidir.
